[build]
target = "riscv64gc-unknown-none-elf"

[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins"]

[target.riscv64gc-unknown-none-elf]
runner = """
qemu-system-riscv64 
-machine virt 
-serial mon:stdio 
-bios default 
-kernel 
"""
